### ISSUE TITLE
How to get web chat  conversation permissions

### ISSUE THREAD

**Issue by felixcheruiyot** [MyPureCloud/platform-client-sdk-python#1]
I'm trying to start a new conversation from a third party app which comes with a chat interface. I guess the best option is to use the web chat endpoints.
Here is part of my code:

    convoApi = PureCloudPlatformClientV2.ConversationsApi()
    convoApi.post_conversations_chats(body)

I keep getting this error `Unable to perform therequested action. You are missing the following permission(s): [conversation:webchat:create]` detailing clearly that I have to get the needed permission. Problem is that the permission is not available under the admin section so that I can add to the needed roles. Could you have any information on how to go around this. My app endpoint is `https://apps.mypurecloud.com.au`

Thanks.

**Comment by PrinceNebulon** [comment]
If the permission is not available in your org, your org is not licensed for web chat. Please contact your sales rep or [PureCloud Support](https://help.mypurecloud.com/articles/contact-purecloud-care/) for information about licensing. 

Once you get the licenses straightened out, please use the [PureCloud Developer Forum](https://developer.mypurecloud.com/forum/) for further development-related questions. Questions or issues with the product itself can be directed to the [PureCloud Community Forum](https://community.genesys.com/communities/purecloud-home?CommunityKey=bab95e9c-6bbe-4a13-8ade-8ec0faf733d4) or support.
