### ISSUE TITLE
LocalDateTime model does not exist.

### ISSUE THREAD

**Issue by PrinceMerluza** [MyPureCloud/platform-client-sdk-python#2]
Not sure if this is the right place to post this.

The **Schedule** model has swagger defined properties: 'start' and 'end' of type **LocalDateTime**.

The only issue is that LocalDateTime is not defined in the platform's models. This becomes an issue and will throw an error when deserializing the Schedule response from ArchitectApi's get_architect_schedule().

The only other model that seems to have a property of type LocalDateTime is EdgeAutoUpdateConfig.

**Comment by PrinceNebulon** [comment]
This is being tracked as API-3670.
