### ISSUE TITLE
sdk wont install on python 3.9 using pycharm

### ISSUE THREAD

**Issue by chadmaggard** [MyPureCloud/platform-client-sdk-python#4]
running pip install PureCloudPlatformClientV2  blows up with lots of errors.

**Comment by timsmithgenesys** [comment]
Hello, please provide more information about your python environment, OS, and what errors you're running into in a new topic on the Genesys Cloud Developer Forum and we can continue the discussion there. Thanks! 

https://developer.mypurecloud.com/forum/c/platform-api/python-sdk/9
